### ISSUE TITLE
Build fails on macOS 11

### ISSUE THREAD

**Issue by DalenW** [instructure/nokogiri-xmlsec-instructure#7]
Not really an issue right now but it could be one. Right now on macOS Big Sur with CLT 12.0, building this gem fails. The fix is to switch back to CLT 11.6, then re-run bundle install/update. However I think this should be looked at or something before the release. 

Here's what the error is, I'm not knowledgable enough with C/C++ to tell you guys what's happening, just that downgrading CLT fixes it. It happens on all ruby versions, I just happened to be one 2.6.4 when I saved this.

> current directory: /Users/dalen/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/nokogiri-xmlsec-instructure-0.9.6/ext/nokogiri_ext_xmlsec
> make "DESTDIR=" clean
> 
> current directory: /Users/dalen/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/nokogiri-xmlsec-instructure-0.9.6/ext/nokogiri_ext_xmlsec
> make "DESTDIR="
> compiling init.c
> compiling nokogiri_decrypt_with_key.c
> nokogiri_decrypt_with_key.c:61:7: error: implicit declaration of function 'nokogiri_root_node' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>       nokogiri_root_node(encCtx->replacedNodeList);
>       ^
> nokogiri_decrypt_with_key.c:21:15: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
>   keyLength = RSTRING_LEN(rb_key);
>             ~ ^~~~~~~~~~~~~~~~~~~
> /Users/dalen/.rbenv/versions/2.6.4/include/ruby-2.6.0/ruby/ruby.h:1000:6: note: expanded from macro 'RSTRING_LEN'
>      RSTRING_EMBED_LEN(str) : \
>      ^~~~~~~~~~~~~~~~~~~~~~
> /Users/dalen/.rbenv/versions/2.6.4/include/ruby-2.6.0/ruby/ruby.h:996:6: note: expanded from macro 'RSTRING_EMBED_LEN'
>      (long)((RBASIC(str)->flags >> RSTRING_EMBED_LEN_SHIFT) & \
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> nokogiri_decrypt_with_key.c:21:15: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
>   keyLength = RSTRING_LEN(rb_key);
>             ~ ^~~~~~~~~~~~~~~~~~~
> /Users/dalen/.rbenv/versions/2.6.4/include/ruby-2.6.0/ruby/ruby.h:1001:28: note: expanded from macro 'RSTRING_LEN'
>      RSTRING(str)->as.heap.len)
>      ~~~~~~~~~~~~~~~~~~~~~~^~~
> 2 warnings and 1 error generated.
> make: *** [nokogiri_decrypt_with_key.o] Error 1
> 
> make failed, exit code 2

**Comment by nasht** [comment]
I just saw this issue while running Xcode 12 on Catalina. 

What resolved it for me was to:
 - install Xcode 11.7 and point the command line tools to it.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/630876/93439468-f2b61180-f911-11ea-8eee-e28270df6694.png">
- ensure that I have run:
 `brew install libxmlsec1 postgresql`

**Comment by DalenW** [comment]
Yup. That's what I did, as stated in my original post. I'm just worried people are gonna run into this way more often with CLT 12.0 being out now.

**Comment by nikoma** [comment]
I do not have Xcode installed and running 'brew install libxmlsec1' fixed it for me.

**Comment by ccutrer** [comment]
I just installed this gem with ruby 2.7.2, Big Sur, Command Line Tools 12.0 with no problems. And yes, libxmlsec1 is a prerequisite. This is also against nokogiri 1.11.3, which has changed several of their internal functions.
